#!/bin/bash

REPORTS_DIR="${BASE_DIR}/reports"
CAPTURE_DIR="${BASE_DIR}/capture"
SESSIONS_DIR="${BASE_DIR}/sessions"

init_report_generator() {
    mkdir -p "$REPORTS_DIR"
}

generate_html_report() {
    local output_file="${1:-${REPORTS_DIR}/report_$(date +%Y%m%d_%H%M%S).html}"
    local session_filter="${2:-}"
    
    echo "Generating HTML report: $output_file"
    local total_captures
    total_captures=$(find "$CAPTURE_DIR" -name "*.json" 2>/dev/null | wc -l)
    
    local unique_ips
    declare -A ip_set
    for capture_file in "${CAPTURE_DIR}"/*.json; do
        if [[ -f "$capture_file" ]]; then
            local ip
            ip=$(jq -r '.ip // "N/A"' "$capture_file" 2>/dev/null)
            if [[ -n "$ip" && "$ip" != "N/A" ]]; then
                ip_set["$ip"]=1
            fi
        fi
    done
    unique_ips=${#ip_set[@]}
    cat > "$output_file" << 'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FishMe Phishing Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f5f5; color: #333; }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 40px; border-radius: 8px; margin-bottom: 30px; }
        .header h1 { font-size: 32px; margin-bottom: 10px; }
        .header p { opacity: 0.9; }
        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .stat-card { background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .stat-card h3 { color: #666; font-size: 14px; margin-bottom: 10px; }
        .stat-card .value { font-size: 36px; font-weight: bold; color: #667eea; }
        .section { background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin-bottom: 30px; }
        .section h2 { color: #333; margin-bottom: 20px; border-bottom: 2px solid #667eea; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #eee; }
        th { background: #f8f9fa; font-weight: 600; color: #555; }
        tr:hover { background: #f8f9fa; }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; }
        .badge-success { background: #10b981; color: white; }
        .badge-warning { background: #f59e0b; color: white; }
        .badge-danger { background: #ef4444; color: white; }
        .footer { text-align: center; color: #666; margin-top: 40px; padding: 20px; }
        @media print { .container { max-width: 100%; } }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>FishMe Phishing Report</h1>
            <p>Generated: DATE_PLACEHOLDER</p>
        </div>
        
        <div class="stats-grid">
            <div class="stat-card">
                <h3>Total Captures</h3>
                <div class="value">TOTAL_CAPTURES_PLACEHOLDER</div>
            </div>
            <div class="stat-card">
                <h3>Unique IPs</h3>
                <div class="value">UNIQUE_IPS_PLACEHOLDER</div>
            </div>
            <div class="stat-card">
                <h3>Success Rate</h3>
                <div class="value">SUCCESS_RATE_PLACEHOLDER%</div>
            </div>
            <div class="stat-card">
                <h3>Active Sessions</h3>
                <div class="value">ACTIVE_SESSIONS_PLACEHOLDER</div>
            </div>
        </div>
        
        <div class="section">
            <h2>Recent Captures</h2>
            <table>
                <thead>
                    <tr>
                        <th>Timestamp</th>
                        <th>Template</th>
                        <th>Username</th>
                        <th>IP Address</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
CAPTURE_TABLE_PLACEHOLDER
                </tbody>
            </table>
        </div>
        
        <div class="section">
            <h2>Template Performance</h2>
            <table>
                <thead>
                    <tr>
                        <th>Template</th>
                        <th>Captures</th>
                        <th>Success Rate</th>
                    </tr>
                </thead>
                <tbody>
TEMPLATE_TABLE_PLACEHOLDER
                </tbody>
            </table>
        </div>
        
        <div class="footer">
            <p>Generated by FishMe v1.0.0 - Phishing Tool</p>
        </div>
    </div>
</body>
</html>
EOF
    sed -i "s/DATE_PLACEHOLDER/$(date '+%Y-%m-%d %H:%M:%S')/g" "$output_file"
    sed -i "s/TOTAL_CAPTURES_PLACEHOLDER/${total_captures}/g" "$output_file"
    sed -i "s/UNIQUE_IPS_PLACEHOLDER/${unique_ips}/g" "$output_file"
    sed -i "s/SUCCESS_RATE_PLACEHOLDER/$(calculate_success_rate)/g" "$output_file"
    sed -i "s/ACTIVE_SESSIONS_PLACEHOLDER/$(get_active_session_count)/g" "$output_file"
    local capture_table=""
    local count=0
    for capture_file in "${CAPTURE_DIR}"/*.json; do
        if [[ -f "$capture_file" && $count -lt 50 ]]; then
            local template
            template=$(basename "$capture_file" .json)
            local timestamp
            timestamp=$(jq -r '.timestamp // "N/A"' "$capture_file" 2>/dev/null)
            local username
            username=$(jq -r '.username // "N/A"' "$capture_file" 2>/dev/null)
            local ip
            ip=$(jq -r '.ip // "N/A"' "$capture_file" 2>/dev/null)
            
            capture_table="${capture_table}
                    <tr>
                        <td>${timestamp}</td>
                        <td><span class=\"badge badge-success\">${template}</span></td>
                        <td>${username}</td>
                        <td>${ip}</td>
                        <td><span class=\"badge badge-success\">Captured</span></td>
                    </tr>"
            ((count++))
        fi
    done
    
    if [[ -z "$capture_table" ]]; then
        capture_table="<tr><td colspan=\"5\" style=\"text-align:center;\">No captures found</td></tr>"
    fi
    
    sed -i "s|CAPTURE_TABLE_PLACEHOLDER|${capture_table}|g" "$output_file"
    local template_table=""
    declare -A template_counts
    for capture_file in "${CAPTURE_DIR}"/*.json; do
        if [[ -f "$capture_file" ]]; then
            local template
            template=$(basename "$capture_file" .json)
            template_counts[$template]=$((${template_counts[$template]:-0} + 1))
        fi
    done
    
    for template in "${!template_counts[@]}"; do
        local count=${template_counts[$template]}
        local rate=100
        template_table="${template_table}
                    <tr>
                        <td><span class=\"badge badge-warning\">${template}</span></td>
                        <td>${count}</td>
                        <td>${rate}%</td>
                    </tr>"
    done
    
    if [[ -z "$template_table" ]]; then
        template_table="<tr><td colspan=\"3\" style=\"text-align:center;\">No template data</td></tr>"
    fi
    
    sed -i "s|TEMPLATE_TABLE_PLACEHOLDER|${template_table}|g" "$output_file"
    echo "HTML report generated: $output_file"
}

generate_pdf_report() {
    local output_file="${1:-${REPORTS_DIR}/report_$(date +%Y%m%d_%H%M%S).pdf}"
    
    if ! command -v wkhtmltopdf &>/dev/null; then
        echo "wkhtmltopdf not found. Install it to generate PDF reports."
        echo "Ubuntu/Debian: sudo apt-get install wkhtmltopdf"
        return 1
    fi
    
    local html_file="${output_file%.pdf}.html"
    generate_html_report "$html_file"
    
    wkhtmltopdf "$html_file" "$output_file" 2>/dev/null
    rm -f "$html_file"
    
    echo "PDF report generated: $output_file"
}

generate_markdown_report() {
    local output_file="${1:-${REPORTS_DIR}/report_$(date +%Y%m%d_%H%M%S).md}"
    
    echo "Generating Markdown report: $output_file"
    cat > "$output_file" << EOF
# FishMe Phishing Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')
**Version:** 1.0.0

---

## Executive Summary

This report provides a comprehensive overview of phishing activities conducted using FishMe.

### Key Metrics

- **Total Captures:** $(find "$CAPTURE_DIR" -name "*.json" 2>/dev/null | wc -l)
- **Unique IPs:** $(get_unique_ip_count)
- **Success Rate:** $(calculate_success_rate)%
- **Active Sessions:** $(get_active_session_count)

---

## Recent Captures

| Timestamp | Template | Username | IP Address | Status |
|-----------|----------|----------|------------|--------|
EOF
    local count=0
    for capture_file in "${CAPTURE_DIR}"/*.json; do
        if [[ -f "$capture_file" && $count -lt 20 ]]; then
            local template
            template=$(basename "$capture_file" .json)
            local timestamp
            timestamp=$(jq -r '.timestamp // "N/A"' "$capture_file" 2>/dev/null)
            local username
            username=$(jq -r '.username // "N/A"' "$capture_file" 2>/dev/null)
            local ip
            ip=$(jq -r '.ip // "N/A"' "$capture_file" 2>/dev/null)
            
            echo "| ${timestamp} | ${template} | ${username} | ${ip} | Captured |" >> "$output_file"
            ((count++))
        fi
    done
    cat >> "$output_file" << EOF

---

## Template Performance

| Template | Captures | Success Rate |
|----------|----------|-------------|
EOF
    declare -A template_counts
    for capture_file in "${CAPTURE_DIR}"/*.json; do
        if [[ -f "$capture_file" ]]; then
            local template
            template=$(basename "$capture_file" .json)
            template_counts[$template]=$((${template_counts[$template]:-0} + 1))
        fi
    done
    
    for template in "${!template_counts[@]}"; do
        local count=${template_counts[$template]}
        echo "| ${template} | ${count} | 100% |" >> "$output_file"
    done
    cat >> "$output_file" << EOF

---

## Recommendations

1. **Review High-Performing Templates:** Focus on templates with higher capture rates for future s.
2. **Analyze IP Patterns:** Review geographic distribution to identify target demographics.
3. **Security:** Use captured data to improve security programs.

---

*This report was generated automatically by FishMe.*
EOF
    echo "Markdown report generated: $output_file"
}

generate_json_report() {
    local output_file="${1:-${REPORTS_DIR}/report_$(date +%Y%m%d_%H%M%S).json}"
    
    echo "Generating JSON report: $output_file"
    
    local total_captures
    total_captures=$(find "$CAPTURE_DIR" -name "*.json" 2>/dev/null | wc -l)
    
    local unique_ips
    unique_ips=$(get_unique_ip_count)
    
    jq -n \
        --arg generated "$(date -Iseconds)" \
        --arg version "1.0.0" \
        --argjson total_captures "$total_captures" \
        --argjson unique_ips "$unique_ips" \
        --arg success_rate "$(calculate_success_rate)" \
        --argjson active_sessions "$(get_active_session_count)" \
        '{
            metadata: {
                generated: $generated,
                version: $version,
                tool: "FishMe"
            },
            summary: {
                total_captures: $total_captures,
                unique_ips: $unique_ips,
                success_rate: $success_rate,
                active_sessions: $active_sessions
            },
            captures: []
        }' > "$output_file"
    
    echo "JSON report generated: $output_file"
}

calculate_success_rate() {
    local total_captures
    total_captures=$(find "$CAPTURE_DIR" -name "*.json" 2>/dev/null | wc -l)
    local total_visits=1000  # Placeholder - would need actual visit tracking
    
    if [[ $total_visits -gt 0 ]]; then
        echo "scale=2; ($total_captures * 100) / $total_visits" | bc
    else
        echo "0"
    fi
}

get_unique_ip_count() {
    declare -A ip_set
    for capture_file in "${CAPTURE_DIR}"/*.json; do
        if [[ -f "$capture_file" ]]; then
            local ip
            ip=$(jq -r '.ip // "N/A"' "$capture_file" 2>/dev/null)
            if [[ -n "$ip" && "$ip" != "N/A" ]]; then
                ip_set["$ip"]=1
            fi
        fi
    done
    echo "${#ip_set[@]}"
}

get_active_session_count() {
    local count=0
    for session_file in "${SESSIONS_DIR}"/*.json; do
        if [[ -f "$session_file" ]]; then
            local status
            status=$(jq -r '.status' "$session_file" 2>/dev/null)
            if [[ "$status" == "active" ]]; then
                ((count++))
            fi
        fi
    done
    echo "$count"
}

list_reports() {
    echo "Available Reports:"
    echo "=================="
    
    if [[ ! -d "$REPORTS_DIR" ]] || [[ -z "$(ls -A "$REPORTS_DIR")" ]]; then
        echo "No reports found."
        return
    fi
    
    local i=1
    for report_file in "${REPORTS_DIR}"/*; do
        if [[ -f "$report_file" ]]; then
            local filename
            filename=$(basename "$report_file")
            local filesize
            filesize=$(du -h "$report_file" | cut -f1)
            local filedate
            filedate=$(stat -c %y "$report_file" 2>/dev/null | cut -d'.' -f1)
            
            printf "  ${GREEN}[%d]${RESET} ${BOLD}%s${RESET} (%s) - %s\n" "$i" "$filename" "$filesize" "$filedate"
            ((i++))
        fi
    done
}

delete_report() {
    local report_name="$1"
    local report_file="${REPORTS_DIR}/${report_name}"
    
    if [[ ! -f "$report_file" ]]; then
        echo "Report not found: $report_name"
        return 1
    fi
    
    rm "$report_file"
    echo "Deleted report: $report_name"
}

generate_all_reports() {
    local base_name="${1:-report_$(date +%Y%m%d_%H%M%S)}"
    
    echo "Generating all report formats..."
    
    generate_html_report "${REPORTS_DIR}/${base_name}.html"
    generate_markdown_report "${REPORTS_DIR}/${base_name}.md"
    generate_json_report "${REPORTS_DIR}/${base_name}.json"
    
    if command -v wkhtmltopdf &>/dev/null; then
        generate_pdf_report "${REPORTS_DIR}/${base_name}.pdf"
    else
        echo "Skipping PDF report (wkhtmltopdf not installed)"
    fi
    
    echo "All reports generated."
}
